# Generated by Django 3.2 on 2021-04-27 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('in_order', models.BooleanField(default=False)),
                ('for_anonymoys_user', models.BooleanField(default=False, verbose_name='сделать заказ анонимно')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Main_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Главная категория',
                'verbose_name_plural': 'Главные категории',
            },
        ),
        migrations.CreateModel(
            name='Tv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Картинка')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('stock', models.IntegerField(verbose_name='Количество единиц товара на складе')),
                ('diagonal', models.CharField(max_length=200, verbose_name='Диагональ дисплея ')),
                ('screen_resolution', models.CharField(max_length=200, verbose_name='Разрешение экрана')),
                ('technology', models.CharField(max_length=250, verbose_name='Технология')),
                ('features', models.CharField(max_length=200, verbose_name='Особености')),
                ('smart_tv', models.BooleanField(default=False, verbose_name='Smart TV')),
                ('hdr', models.BooleanField(default=False, verbose_name='HDR')),
                ('wi_fi', models.BooleanField(default=False, verbose_name='WI_FI')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Телевизор',
                'verbose_name_plural': 'Телевизоры',
            },
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Картинка')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('stock', models.IntegerField(verbose_name='Количество единиц товара на складе')),
                ('diagonal', models.CharField(max_length=200, verbose_name='Диагональ дисплея ')),
                ('screen_resolution', models.CharField(max_length=200, verbose_name='Разрешение экрана')),
                ('system', models.CharField(max_length=200, verbose_name='Операционная система')),
                ('memory_size', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Обьем встроенной  паняти')),
                ('main_camera', models.CharField(max_length=200, verbose_name='Основная камера')),
                ('front_camera', models.CharField(max_length=200, verbose_name='Фрональная камера')),
                ('features', models.CharField(max_length=200, verbose_name='Особености')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Планшет',
                'verbose_name_plural': 'Планшеты',
            },
        ),
        migrations.CreateModel(
            name='Smartphones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Картинка')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('stock', models.IntegerField(verbose_name='Количество единиц товара на складе')),
                ('diagonal', models.CharField(max_length=200, verbose_name='Диагональ дисплея ')),
                ('screen_resolution', models.CharField(max_length=200, verbose_name='Разрешение экрана')),
                ('system', models.CharField(max_length=200, verbose_name='Операционная система')),
                ('sim_quantity', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Количество SIM')),
                ('memory_size', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Обьем встроенной  паняти')),
                ('main_camera', models.CharField(max_length=200, verbose_name='Основная камера')),
                ('front_camera', models.CharField(max_length=200, verbose_name='Фрональная камера')),
                ('features', models.CharField(max_length=200, verbose_name='Особености')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Смартфон',
                'verbose_name_plural': 'Смартфоны',
            },
        ),
        migrations.CreateModel(
            name='Projector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Картинка')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('stock', models.IntegerField(verbose_name='Количество единиц товара на складе')),
                ('screen_resolution', models.CharField(max_length=200, verbose_name='Разрешение экрана')),
                ('max_screen_resolution', models.CharField(max_length=200, verbose_name='Мфксимальное разрешение экрана ')),
                ('three_d', models.BooleanField(default=False, verbose_name='Поддержка 3D')),
                ('Max_projection_distance', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Максимальное проекционное расстояние')),
                ('min_projection_distance', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Минимальное проекционное расстояние')),
                ('features', models.CharField(max_length=200, verbose_name='Особености')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Проектор',
                'verbose_name_plural': 'Проекторы',
            },
        ),
        migrations.CreateModel(
            name='Pc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Картинка')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('stock', models.IntegerField(verbose_name='Количество единиц товара на складе')),
                ('cpu', models.CharField(max_length=200, verbose_name='Модель процессора')),
                ('number_of_cores', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Количество ядер')),
                ('frequency_cpu', models.CharField(max_length=200, verbose_name='Чистота процессора')),
                ('ozu', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Обьем оперативной памяти')),
                ('drive_volume', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Обьем жесткого диска')),
                ('system', models.CharField(max_length=200, verbose_name='Операционная система')),
                ('video_adapter_chipset', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Чипсет видеоадаптера')),
                ('videoadapter', models.CharField(max_length=200, verbose_name='Видеоадаптер')),
                ('video_memory', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Обьем видеоадаптера')),
                ('features', models.CharField(max_length=200, verbose_name='Особености')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Персональный компьютер',
                'verbose_name_plural': 'Персональные компьютеры',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('coment', models.TextField(blank=True, verbose_name='коментарий')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В обработке'), ('ready', 'В пути'), ('completed', 'Выполнен')], default='new', max_length=150, verbose_name='Статус заказа')),
                ('buying_type', models.CharField(choices=[('self', 'Самовывоз'), ('delivery', 'Доставка')], default='self', max_length=100, verbose_name='Тип доставки')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата получения')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.cart', verbose_name='Корзина')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Laptops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Картинка')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('stock', models.IntegerField(verbose_name='Количество единиц товара на складе')),
                ('diagonal', models.CharField(max_length=200, verbose_name='Диагональ дисплея ')),
                ('screen_resolution', models.CharField(max_length=200, verbose_name='Разрешение экрана')),
                ('videoadapter', models.CharField(max_length=200, verbose_name='Видеоадаптер')),
                ('system', models.CharField(max_length=200, verbose_name='Операционная система')),
                ('cpu', models.CharField(max_length=200, verbose_name='Модель процессора')),
                ('frequency_cpu', models.CharField(max_length=200, verbose_name='Чистота процессора')),
                ('ozu', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Обьем оперативной памяти')),
                ('disk_type', models.CharField(max_length=200, verbose_name='Тип жесткого диска')),
                ('drive_volume', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Обьем накопителя')),
                ('video_adapter_chipset', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Чипсет видеоадаптера')),
                ('video_memory', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Обьем видеоадаптера')),
                ('features', models.CharField(max_length=200, verbose_name='Особености')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Ноутбук',
                'verbose_name_plural': 'Ноутбуки',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='orders', to='shop.Order', verbose_name='Заказы пользователя'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.main_category', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена')),
                ('cart_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cart', verbose_name='Корзина')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'продукт корзины',
                'verbose_name_plural': 'Продукты корзин',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.customer', verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='shop.CartProduct'),
        ),
    ]
